package com.lobster.input.ui.theme

import androidx.compose.ui.graphics.Color

// Light — 现代水蓝 + 扁平柔和
val md_theme_light_primary = Color(0xFF0A84C4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCDEEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF073A56)
val md_theme_light_secondary = Color(0xFF2BA7E0)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7EFFB)
val md_theme_light_onSecondaryContainer = Color(0xFF073A56)
val md_theme_light_tertiary = Color(0xFF06B6D4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFF4FB)
val md_theme_light_onTertiaryContainer = Color(0xFF053B45)
val md_theme_light_error = Color(0xFFE5484D)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFDE2E2)
val md_theme_light_onErrorContainer = Color(0xFF5A1216)
val md_theme_light_background = Color(0xFFF4FAFE)
val md_theme_light_onBackground = Color(0xFF0B3A52)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0B3A52)
val md_theme_light_surfaceVariant = Color(0xFFECF5FB)
val md_theme_light_onSurfaceVariant = Color(0xFF5A8095)
val md_theme_light_outline = Color(0xFFDCEBF4)
val md_theme_light_outlineVariant = Color(0xFFE6F1F8)

// Dark — 同色相深海蓝
val md_theme_dark_primary = Color(0xFF5FC4F0)
val md_theme_dark_onPrimary = Color(0xFF052E45)
val md_theme_dark_primaryContainer = Color(0xFF0E4665)
val md_theme_dark_onPrimaryContainer = Color(0xFFCDEEFB)
val md_theme_dark_secondary = Color(0xFF8AD3F4)
val md_theme_dark_onSecondary = Color(0xFF052E45)
val md_theme_dark_secondaryContainer = Color(0xFF1C3850)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7EFFB)
val md_theme_dark_tertiary = Color(0xFF67DDF0)
val md_theme_dark_onTertiary = Color(0xFF043640)
val md_theme_dark_tertiaryContainer = Color(0xFF0C4C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFCFF4FB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF5A1216)
val md_theme_dark_errorContainer = Color(0xFF7A2A2D)
val md_theme_dark_onErrorContainer = Color(0xFFFDE2E2)
val md_theme_dark_background = Color(0xFF0A1F2E)
val md_theme_dark_onBackground = Color(0xFFE6F3FB)
val md_theme_dark_surface = Color(0xFF10293B)
val md_theme_dark_onSurface = Color(0xFFE6F3FB)
val md_theme_dark_surfaceVariant = Color(0xFF1C3850)
val md_theme_dark_onSurfaceVariant = Color(0xFF9FC2D4)
val md_theme_dark_outline = Color(0xFF33536A)
val md_theme_dark_outlineVariant = Color(0xFF274458)
